name: 'EA Repo List'
description: 'Retrieve all internal repositories from a GitHub Enteprise Account'
inputs:
  enterprise:  
    description: 'Name of the enteprise account'
    required: true
  outputFilename:  
    description: 'File to write the repo list to'
    required: false
  token:  
    description: 'A GitHub Personal Access Token allowing to browse the Enterprise Account'
    required: true
outputs:
  repo-list: 
    description: 'The list of repositories'
runs:
  using: 'node12'
  main: 'index.js'
